package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"go.uber.org/zap"
)

// fileData описывает содержимое генерируемого файла: имя пакета и список структур.
type fileData struct {
	Package string
	Structs []structData
}

type structData struct {
	Name     string
	Receiver string
	Lines    []string
}

const resetTemplate = `// Code generated by cmd/reset; DO NOT EDIT.
package {{ .Package }}

{{ range .Structs }}
func ({{ .Receiver }} *{{ .Name }}) Reset() {
	if {{ .Receiver }} == nil {
		return
	}
{{- range .Lines }}
	{{ . }}
{{- end }}
}
{{ end }}`

var tmpl = template.Must(template.New("reset").Parse(resetTemplate))

var sugar *zap.SugaredLogger

func init() {
	logger, err := zap.NewDevelopment()
	if err != nil {
		log.Printf("Failed to create zap logger: %v", err)
		logger = zap.NewNop()
	}
	sugar = logger.Sugar()
}

func main() {
	defer sugar.Sync()

	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		// пропускаем скрытые директории, vendor, testdata
		name := info.Name()
		if name != "." && (strings.HasPrefix(name, ".") || name == "vendor" || name == "testdata") {
			return filepath.SkipDir
		}

		processDir(path)
		return nil
	})
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

func processDir(dir string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return
	}

	for _, pkg := range pkgs {
		var structs []structInfo

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Doc == nil {
					continue
				}

				// ищем комментарий // generate:reset
				hasReset := false
				for _, c := range genDecl.Doc.List {
					if strings.TrimSpace(c.Text) == "// generate:reset" {
						hasReset = true
						break
					}
				}
				if !hasReset {
					continue
				}

				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					structs = append(structs, structInfo{
						name:   ts.Name.Name,
						fields: st.Fields.List,
					})
				}
			}
		}

		if len(structs) == 0 {
			continue
		}

		// собираем данные для шаблона
		data := fileData{Package: pkg.Name}
		for _, s := range structs {
			r := strings.ToLower(s.name[:1])
			sd := structData{Name: s.name, Receiver: r}

			for _, field := range s.fields {
				for _, name := range field.Names {
					line := resetLine(r, name.Name, field.Type)
					if line != "" {
						sd.Lines = append(sd.Lines, line)
					}
				}
			}

			data.Structs = append(data.Structs, sd)
		}

		// выполняем шаблон
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, data); err != nil {
			sugar.Errorw("template execute error", "dir", dir, "err", err)
			return
		}

		// форматируем результат через go/format (аналог gofmt)
		formatted, err := format.Source(buf.Bytes())
		if err != nil {
			sugar.Errorw("format error", "dir", dir, "err", err)
			return
		}

		outPath := filepath.Join(dir, "reset.gen.go")
		if err := os.WriteFile(outPath, formatted, 0644); err != nil {
			sugar.Errorw("write file error", "path", outPath, "err", err)
			return
		}
		sugar.Infow("generated file", "path", outPath)
	}
}

// нулевые значения для примитивов
var zeroValues = map[string]string{
	"int": "0", "int8": "0", "int16": "0", "int32": "0", "int64": "0",
	"uint": "0", "uint8": "0", "uint16": "0", "uint32": "0", "uint64": "0",
	"float32": "0", "float64": "0",
	"string": `""`, "bool": "false",
	"byte": "0", "rune": "0",
}

func resetLine(recv, fieldName string, fieldType ast.Expr) string {
	f := recv + "." + fieldName

	switch t := fieldType.(type) {
	case *ast.Ident:
		// примитив — обнуляем
		if zero, ok := zeroValues[t.Name]; ok {
			return fmt.Sprintf("%s = %s", f, zero)
		}
		// вложенная структура — вызываем Reset()
		return fmt.Sprintf("%s.Reset()", f)

	case *ast.ArrayType:
		if t.Len == nil {
			// слайс — обрезаем
			return fmt.Sprintf("%s = %s[:0]", f, f)
		}
		return ""

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", f)

	case *ast.StarExpr:
		// указатель
		if ident, ok := t.X.(*ast.Ident); ok {
			if zero, ok := zeroValues[ident.Name]; ok {
				// указатель на примитив
				return fmt.Sprintf("if %s != nil {\n*%s = %s\n}", f, f, zero)
			}
			// указатель на структуру — вызываем Reset()
			return fmt.Sprintf("%s.Reset()", f)
		}
		return ""

	default:
		return ""
	}
}
