package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func main() {
	filepath.Walk(".", func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		// пропускаем скрытые директории, vendor, testdata
		name := info.Name()
		if name != "." && (strings.HasPrefix(name, ".") || name == "vendor" || name == "testdata") {
			return filepath.SkipDir
		}

		processDir(path)
		return nil
	})
}

type structInfo struct {
	name   string
	fields []*ast.Field
}

func processDir(dir string) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, parser.ParseComments)
	if err != nil {
		return
	}

	for _, pkg := range pkgs {
		var structs []structInfo

		for _, file := range pkg.Files {
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Doc == nil {
					continue
				}

				// ищем комментарий // generate:reset
				hasReset := false
				for _, c := range genDecl.Doc.List {
					if strings.TrimSpace(c.Text) == "// generate:reset" {
						hasReset = true
						break
					}
				}
				if !hasReset {
					continue
				}

				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}
					st, ok := ts.Type.(*ast.StructType)
					if !ok {
						continue
					}
					structs = append(structs, structInfo{
						name:   ts.Name.Name,
						fields: st.Fields.List,
					})
				}
			}
		}

		if len(structs) == 0 {
			continue
		}

		// генерируем код
		var buf strings.Builder
		buf.WriteString("// Code generated by cmd/reset; DO NOT EDIT.\n")
		fmt.Fprintf(&buf, "package %s\n\n", pkg.Name)

		for _, s := range structs {
			r := strings.ToLower(s.name[:1])
			fmt.Fprintf(&buf, "func (%s *%s) Reset() {\n", r, s.name)
			fmt.Fprintf(&buf, "if %s == nil {\nreturn\n}\n", r)

			for _, field := range s.fields {
				for _, name := range field.Names {
					line := resetLine(r, name.Name, field.Type)
					if line != "" {
						buf.WriteString(line + "\n")
					}
				}
			}

			buf.WriteString("}\n\n")
		}

		// форматируем через go/format (аналог gofmt)
		formatted, err := format.Source([]byte(buf.String()))
		if err != nil {
			fmt.Fprintf(os.Stderr, "format error in %s: %v\n", dir, err)
			return
		}

		outPath := filepath.Join(dir, "reset.gen.go")
		os.WriteFile(outPath, formatted, 0644)
		fmt.Printf("generated %s\n", outPath)
	}
}

// нулевые значения для примитивов
var zeroValues = map[string]string{
	"int": "0", "int8": "0", "int16": "0", "int32": "0", "int64": "0",
	"uint": "0", "uint8": "0", "uint16": "0", "uint32": "0", "uint64": "0",
	"float32": "0", "float64": "0",
	"string": `""`, "bool": "false",
	"byte": "0", "rune": "0",
}

func resetLine(recv, fieldName string, fieldType ast.Expr) string {
	f := recv + "." + fieldName

	switch t := fieldType.(type) {
	case *ast.Ident:
		// примитив — обнуляем
		if zero, ok := zeroValues[t.Name]; ok {
			return fmt.Sprintf("%s = %s", f, zero)
		}
		// вложенная структура — вызываем Reset()
		return fmt.Sprintf("%s.Reset()", f)

	case *ast.ArrayType:
		if t.Len == nil {
			// слайс — обрезаем
			return fmt.Sprintf("%s = %s[:0]", f, f)
		}
		return ""

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", f)

	case *ast.StarExpr:
		// указатель
		if ident, ok := t.X.(*ast.Ident); ok {
			if zero, ok := zeroValues[ident.Name]; ok {
				// указатель на примитив
				return fmt.Sprintf("if %s != nil {\n*%s = %s\n}", f, f, zero)
			}
			// указатель на структуру — вызываем Reset()
			return fmt.Sprintf("%s.Reset()", f)
		}
		return ""

	default:
		return ""
	}
}
